import { addDays, format, subDays } from "date-fns";
import type {
  CalendarItem,
  Goal,
  InboxItem,
  SocialAccount,
  SocialSnapshot,
  Subscription,
  Task,
} from "./types";

// A fixed demo clock keeps the mock experience coherent across dates and time zones.
export const DEMO_TODAY = "2026-09-20";
export const demoDate = new Date(2026, 8, 20, 10);
export const socialAccounts: SocialAccount[] = [
  {
    id: "tiktok",
    platform: "tiktok",
    displayName: "TikTok",
    metricLabel: "Followers",
    followers: 31428,
    previousFollowers: 31144,
    change: 284,
  },
  {
    id: "instagram",
    platform: "instagram",
    displayName: "Instagram",
    metricLabel: "Followers",
    followers: 4829,
    previousFollowers: 4841,
    change: -12,
  },
  {
    id: "youtube",
    platform: "youtube",
    displayName: "YouTube",
    metricLabel: "Subscribers",
    followers: 2941,
    previousFollowers: 2848,
    change: 93,
  },
];
export const socialSnapshots: SocialSnapshot[] = socialAccounts.flatMap(
  (account) =>
    Array.from({ length: 366 }, (_, index) => {
      const daysAgo = 365 - index;
      const recent = daysAgo <= 7;
      const followers = recent
        ? account.followers - (account.change * daysAgo) / 7
        : account.previousFollowers * (0.61 + 0.39 * (index / 358)) +
          Math.sin(index / 11) * account.followers * 0.003;
      return {
        platform: account.platform,
        date: format(subDays(demoDate, daysAgo), "yyyy-MM-dd"),
        followers: Math.round(followers),
      };
    }),
);
export const tasks: Task[] = [
  {
    id: "t1",
    title: "Finish dashboard design",
    date: DEMO_TODAY,
    completed: false,
    priority: "High",
    category: "Development",
    scope: "daily",
  },
  {
    id: "t2",
    title: "Record the desk setup TikTok",
    date: DEMO_TODAY,
    completed: false,
    priority: "Medium",
    category: "Content",
    scope: "daily",
  },
  {
    id: "t3",
    title: "Evening strength session",
    date: DEMO_TODAY,
    completed: false,
    priority: "Low",
    category: "Health",
    scope: "daily",
  },
  {
    id: "t4",
    title: "Plan the week ahead",
    date: DEMO_TODAY,
    completed: true,
    priority: "Medium",
    category: "Personal",
    scope: "daily",
  },
  {
    id: "t5",
    title: "Read 20 pages",
    date: DEMO_TODAY,
    completed: true,
    priority: "Low",
    category: "Personal",
    scope: "daily",
  },
  {
    id: "t6",
    title: "Edit YouTube intro",
    date: DEMO_TODAY,
    completed: true,
    priority: "High",
    category: "Content",
    scope: "daily",
  },
  {
    id: "t7",
    title: "Clear the workspace",
    date: DEMO_TODAY,
    completed: true,
    priority: "Low",
    category: "Personal",
    scope: "daily",
  },
  {
    id: "t8",
    title: "Outline the iPhone review",
    date: "2026-09-21",
    completed: false,
    priority: "High",
    category: "Content",
    scope: "daily",
  },
  {
    id: "t9",
    title: "Book a dentist appointment",
    date: "2026-09-22",
    completed: false,
    priority: "Low",
    category: "Personal",
    scope: "daily",
  },
  {
    id: "t10",
    title: "Review website accessibility",
    date: "2026-09-23",
    completed: false,
    priority: "Medium",
    category: "Development",
    scope: "daily",
  },
  {
    id: "t11",
    title: "Organize video footage",
    date: "2026-09-18",
    completed: false,
    priority: "Medium",
    category: "Content",
    scope: "daily",
  },
  {
    id: "t12",
    title: "Renew domain contact details",
    date: "2026-09-19",
    completed: false,
    priority: "Low",
    category: "Admin",
    scope: "daily",
  },
];
const monthlySeeds: [string, Task["category"]][] = [
  ["Finish iPhone video", "Content"],
  ["Upload 3 YouTube videos", "Content"],
  ["Record router video", "Content"],
  ["Plan October content", "Content"],
  ["Fix Clip Optimiser export", "Development"],
  ["Finish dashboard", "Development"],
  ["Deploy portfolio update", "Development"],
  ["Organize room", "Personal"],
  ["Read two books", "Personal"],
  ["Review monthly budget", "Admin"],
  ["Complete 12 workouts", "Health"],
];
export const monthlyTasks: Task[] = monthlySeeds.map(
  ([title, category], i) => ({
    id: `m${i}`,
    title,
    category,
    date: "2026-09-30",
    completed: i >= 5,
    priority: i < 2 ? "High" : "Medium",
    scope: "monthly",
  }),
);
export const goals: Goal[] = [
  {
    id: "g1",
    title: "Grow my YouTube community",
    description: "Make useful things. Find the people who need them.",
    currentValue: 2941,
    targetValue: 5000,
    unit: "subscribers",
    deadline: "2026-12-31",
    category: "Creator",
  },
  {
    id: "g2",
    title: "Launch Clip Optimiser",
    description: "Bring a simpler video workflow into the world.",
    currentValue: 48,
    targetValue: 100,
    unit: "%",
    deadline: "2026-11-15",
    category: "Development",
  },
  {
    id: "g3",
    title: "Build my investment habit",
    description: "A little consistency today. More freedom tomorrow.",
    currentValue: 650000,
    targetValue: 1000000,
    unit: "NGN",
    deadline: "2026-12-31",
    category: "Personal",
  },
  {
    id: "g4",
    title: "Read 12 good books",
    description: "Make a little more room for a different perspective.",
    currentValue: 8,
    targetValue: 12,
    unit: "books",
    deadline: "2026-12-31",
    category: "Personal",
  },
];
export const subscriptions: Subscription[] = [
  {
    id: "s1",
    name: "ChatGPT Plus",
    amount: 32000,
    currency: "NGN",
    billingCycle: "monthly",
    renewalDate: "2026-09-26",
    category: "Productivity",
    icon: "spark",
    active: true,
  },
  {
    id: "s2",
    name: "Adobe Creative Cloud",
    amount: 12500,
    currency: "NGN",
    billingCycle: "monthly",
    renewalDate: "2026-09-24",
    category: "Creative",
    icon: "adobe",
    active: true,
  },
  {
    id: "s3",
    name: "iCloud+",
    amount: 4500,
    currency: "NGN",
    billingCycle: "monthly",
    renewalDate: "2026-10-02",
    category: "Storage",
    icon: "cloud",
    active: true,
  },
  {
    id: "s4",
    name: "YouTube Premium",
    amount: 1700,
    currency: "NGN",
    billingCycle: "monthly",
    renewalDate: "2026-09-29",
    category: "Entertainment",
    icon: "youtube",
    active: true,
  },
  {
    id: "s5",
    name: "Personal domain",
    amount: 18000,
    currency: "NGN",
    billingCycle: "yearly",
    renewalDate: "2026-11-14",
    category: "Development",
    icon: "globe",
    active: true,
  },
  {
    id: "s6",
    name: "Spotify",
    amount: 1300,
    currency: "NGN",
    billingCycle: "monthly",
    renewalDate: "2026-10-06",
    category: "Entertainment",
    icon: "music",
    active: true,
  },
];
export const inboxItems: InboxItem[] = [
  {
    id: "i1",
    category: "Subscription",
    title: "Adobe renews in 4 days",
    description: "₦12,500 · Creative Cloud monthly plan",
    date: "2026-09-20T09:00:00",
    read: false,
    action: "View subscription",
    href: "/subscriptions",
  },
  {
    id: "i2",
    category: "Tasks",
    title: "Two things need a little attention",
    description: "You have 2 overdue tasks. Make room or reschedule.",
    date: "2026-09-20T08:30:00",
    read: false,
    action: "Review tasks",
    href: "/tasks?view=upcoming",
  },
  {
    id: "i3",
    category: "Goals",
    title: "Time for your weekly check-in",
    description: "How is your YouTube goal coming along?",
    date: "2026-09-20T08:00:00",
    read: false,
    action: "Update goal",
    href: "/goals",
  },
  {
    id: "i4",
    category: "Creator",
    title: "A little growth, a lot of possibility",
    description: "Your TikTok community grew by 284 this week.",
    date: "2026-09-19T16:00:00",
    read: true,
    action: "See your audience",
    href: "/creator",
  },
  {
    id: "i5",
    category: "Review",
    title: "September is taking shape",
    description:
      "6 of your 11 monthly tasks are complete. Take a look at what is left.",
    date: "2026-09-18T09:00:00",
    read: true,
    action: "Review this month",
    href: "/tasks?view=monthly",
  },
];
export const calendarItems: CalendarItem[] = [
  {
    id: "c1",
    title: "Sunday reset",
    date: DEMO_TODAY,
    category: "task",
    href: "/tasks",
  },
  {
    id: "c2",
    title: "Film iPhone review",
    date: format(addDays(demoDate, 2), "yyyy-MM-dd"),
    category: "task",
    href: "/tasks",
  },
];
